services:
  api_prontocardio:
    image: api_prontocardio
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host-gateway:host-gateway"
    restart: unless-stopped
